### DISCUSSION TITLE
When I select image. No border show around that.

### DISCUSSION THREAD

**Discussion by patsornk** [ueberdosis/tiptap#1749] [General Questions] [answered]
Can anyone fix my problem TT.
![image](https://user-images.githubusercontent.com/76081944/130020904-2825cbef-42ee-48cb-826d-2813c6cccffa.png)

**Comment by philippkuehn** [comment, marked as answer]
There is some CSS needed:
```css
.ProseMirror-selectednode {
  outline: 3px solid red;
}
```

You could also take a look at the [Focus](https://www.tiptap.dev/api/extensions/focus) extension.
