### DISCUSSION TITLE
Multiple Placeholders example?

### DISCUSSION THREAD

**Discussion by upendra-web** [ueberdosis/tiptap#190] [General Questions]
First of all, Thank you for making such an awesome WYSIWYG editor.

Can anyone give me an example where we can use multiple placeholders, like for example placeholder text for a list item saying 'Enter what to do', something like an input?

Thanks in advance.

Something like the below example:
![screenshot 92](https://user-images.githubusercontent.com/43108965/52310997-64ef1200-29cb-11e9-9c10-f24909e17df4.jpg)

**Comment by swuecho** [comment]
Hi @upendra-web, 

Did you find the solution? Thanks.

**Comment by upendra-web** [comment]
Nope, dude. I couldn't find a solution.

**Comment by AldrinSalazar** [comment]
Any solution for this?

**Comment by charlesfrisbee** [comment]
I know it's been a while but hopefully this may help others.

The placeholder extension exposes a `node` object that may be used to specify different placeholders per node:

```js
Placeholder.configure({
  placeholder: ({ node }) => {

    if (node.type.name === "heading") {
      return "Heading placeholder";
    }

    return "Default placeholder";
  },
}),

```
The default Tiptap editor with the placeholder plugin only displays the placeholder for the first node (provided it is empty).

Add the following css to display placeholders for all blocks.

```css 
.ProseMirror .is-editor-empty:first-child::before {
  content: attr(data-placeholder);
  float: left;
  color: #ced4da;
  pointer-events: none;
  height: 0;
}

.ProseMirror .is-empty::before {
  content: attr(data-placeholder);
  float: left;
  color: #ced4da;
  pointer-events: none;
  height: 0;
}
```
