### DISCUSSION TITLE
How to change the text alignment of the placeholder?

### DISCUSSION THREAD

**Discussion by amirhhashemi** [ueberdosis/tiptap#2864] [General Questions] [answered]
There is no way to right-align the placeholder (using the[ placeholder plugin](https://tiptap.dev/api/extensions/placeholder)). I've tried every single css and html attribute and tag but I can't make the placeholder right-aligned. Is that even possible?

**Comment by pointnet** [comment, marked as answer]
```css
.ProseMirror p.is-editor-empty:first-child:before {
  float: right;
}
```

**Reply by amirhhashemi** [reply]
Thank you, man. You saved my day.

**Reply by ankojh** [reply]
@pointnet how can this be configured based on the current text alignment - ['left', 'center', 'right']?

**Reply by dukenguyen5gl** [reply]
@ankojh Not sure you solved it or not. Just change the css of placeholder to
`float: inherit`

**Reply by sandstone991** [reply]
float: inherit places the caret at the end of the placeholder for me.

Instead this is what worked for me 

```css
  .tiptap .is-editor-empty:first-child::before {
            float: left;
            height: 0;
        }

   .tiptap .is-editor-empty[style*="text-align: center"]:first-child::before {
            float: inherit;
            height: 0;
        }

   .tiptap .is-editor-empty[style*="text-align: right"]:first-child::before {
            float: right;
        }
```

Sorry for unformatted code.
