### DISCUSSION TITLE
How to add element style from JS code?

### DISCUSSION THREAD

**Discussion by ngekoding** [ueberdosis/tiptap#3562] [General Questions]
Hi friends,
I want to add a style from JS code for ordered list, I just try this code with no luck.

What actually I want is changing the counter-reset for the list based on the start attribute.

```js
const orderedList = document.querySelectorAll('.ProseMirror ol')
for (let i = 0; i < orderedList.length; i++) {
  const start = orderedList[i].getAttribute('start')
  if (start) {
    orderedList[i].style.counterReset = 'li ' + (parseInt(start) - 1)
  }
}
```

And I have scss style for the `ol` like this:

```scss
ol {
  padding: 0;
  list-style-position: inside;
  counter-reset: li;
  li {
    display: grid;
    grid-template-columns: min-content 1fr;
    counter-increment: li;
    &::before {
      content: counter(li) '. ';
    }
  }
}
```

Thanks in advance
