### ISSUE TITLE
Placeholder doesn't work on react component

### ISSUE THREAD

**Issue by devrsi0n** [ueberdosis/tiptap#2141]
### What’s the bug you are facing?

Placeholder doesn't work on react component, it only adds a `data-placeholder` attributes with no `:before` element.
![image](https://user-images.githubusercontent.com/7880675/140637770-2ba1e4ba-1b93-412f-8bd0-f615751d2c8b.png)

### How can we reproduce the bug on our side?

Click the codesandbox below.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/stupefied-rosalind-3mch2?file=/src/App.js

### What did you expect to happen?

Render a placeholder

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
you need to add your custom CSS as shown in the docs

```css
/* Placeholder (at the top) */
.ProseMirror p.is-editor-empty:first-child::before {
  content: attr(data-placeholder);
  float: left;
  color: #adb5bd;
  pointer-events: none;
  height: 0;
}

/* Placeholder (on every new line) */
/*.ProseMirror p.is-empty::before {
  content: attr(data-placeholder);
  float: left;
  color: #adb5bd;
  pointer-events: none;
  height: 0;
}*/

```
