### ISSUE TITLE
[Bug]: Chrome: Selecting inline image at end of paragraph with mouse from right

### ISSUE THREAD

**Issue by forresto** [ueberdosis/tiptap#4935]
### Which packages did you experience the bug in?

core, starter-kit, extension-image 

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

When selecting with the mouse from the right on a paragraph like this:

![image](https://github.com/ueberdosis/tiptap/assets/395307/531293c4-017d-4f4e-954e-3330dea5ca02)

It wasn't possible to select the last inline image. The drop cursor would just show. 

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/tiptap-inline-image-nmsq2q?file=%2Fsrc%2Findex.ts%3A8%2C1

### What did you expect to happen?

It works on the simplest ProseMirror Demo: https://prosemirror.net/examples/dino/ 

### Anything to add? (optional)

The only difference that I found were these styles that were in the ProseMirror demo but not TipTap. By adding these styles, it works. I don't know if they will adversely affect something else.

``` css
      /** Fixes text selection around inline images:
      * the only differences that I could find between
      * stock TipTap and https://prosemirror.net/examples/dino/
      */
      .ProseMirror [draggable][contenteditable="false"] {
        user-select: text;
      }
      img.ProseMirror-separator {
        width: 0px !important;
        height: 0px !important;
      }
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖
