### ISSUE TITLE
[Bug]: Placholder at a certain node not showing, specifically a taskList node,

### ISSUE THREAD

**Issue by MorpheusZI** [ueberdosis/tiptap#5073]
### Which packages did you experience the bug in?

placeholder, react, core

### What Tiptap version are you using?

2.3.0

### What’s the bug you are facing?

currently using the placeholder extension. and im trying to to set a custom placeholder on certain nodes, rn i need the placeholder to display a certain text when the current node is a taskList node.

 i tried following the steps from the [documentation](https://tiptap.dev/docs/editor/api/extensions/placeholder#placeholder) by checking the node name, but it still doesnt display the custom placeholder even if though current node is a taskList node.
 
 heres my current attempt: 
 ```ts
 const aditor = useEditor({
     // other stuff
      Placeholder.configure({
        placeholder: ({ editor, node }) => {
          console.log(node, "hahay")
          if (node.type.name === "taskList") {
            return "this is a taskList"
          }
          return "this is an empty node"
        },
      }),
    ],
    editorProps: {
      attributes: {
        class: "w-full px-3 py-4 text-black outline-none"
      }
    },
  })
  ```
with the code above the editor displays like this: 
![image](https://github.com/ueberdosis/tiptap/assets/96110952/a71639ac-3c52-4f3f-8dff-4fdf73192ba9)
(above is a photo of the same editor)

and yes i have written the css too: 
```css
.tiptap p.is-editor-empty:first-child::before {
  color: #adb5bd;
  content: attr(data-placeholder);
  float: left;
  height: 0;
  pointer-events: none;
}
.tiptap p.is-empty::before {
  color: #adb5bd;
  content: attr(data-placeholder);
  float: left;
  height: 0;
  pointer-events: none;
}
```

### What browser are you using?

Chrome

### What did you expect to happen?

Expected to see a placeholder saying "This is a taskList node" when the cursor is at a empty taskList node

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by skix123** [comment]
I faced a similar issue and hacked it with CSS like this:

```css
.tiptap {
        /* styles placeholders but doesn't display them (note missing `content` prop) */
	[data-placeholder]::before {
		float: left;
		color: hsl(var(--muted-foreground));
		pointer-events: none;
		height: 0;
	}

        /* special case if editor is empty */
	& > p.is-editor-empty:first-child::before {
		content: 'Write a description...';
	}

        /* show default placeholders for headings and paragraphs */
	& > :is(p, h1, h2, h3, h4, h5, h6)[data-placeholder]::before {
		content: attr(data-placeholder);
	}

        /* placeholder for ordered and bullet list items */
	ol p[data-placeholder]::before,
	ul p[data-placeholder]::before {
		content: 'Enter item...';
	}

        /* placeholder for checklist items */
	ul div > p[data-placeholder]::before {
		content: 'Enter checklist item...';
	}
}
```

Not sure how it behaves with more advanced editors with some extra extensions but should do the job for simpler ones
