### ISSUE TITLE
Custom class and outline in ProseMirror editor 

### ISSUE THREAD

**Issue by Sogl** [ueberdosis/tiptap#524]
How can I add custom class to `ProseMirror` generated html element? I looked [here](https://tiptap.scrumpy.io/docs/api/classes.html#editor) and nothing about custom classes found.

I tried to use workaround here adding Bulma `content` class and copy `textarea` css to scoped

Vue:
```vue
<editor-content class="content" :editor="editor" />
```

Scoped css with copied `textarea` style:
```scss
<style lang="scss" type="text/scss" scoped>
    .content {
        box-shadow: inset 0 1px 2px rgba(10, 10, 10, 0.1);
        border: 1px solid #dbdbdb;
        display: block;
        max-width: 100%;
        min-width: 100%;
        padding: 0.625em;
        resize: vertical;
        background-color: white;
        border-radius: 4px;
    }
</style>
```

Global css (here just because scoped styles don't affect to Tiptap generated DOM elements):
```scss
//disable outline
.content {
    .ProseMirror {
        outline: none;
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/7556290/69095948-72f6b680-0a64-11ea-8cab-b7187ff5e58e.png)

With that thing I have `div` wrapper and no outline. And how ugly it looks with outline:
![image](https://user-images.githubusercontent.com/7556290/69096116-db459800-0a64-11ea-9764-c7b44cb42a8a.png)

Any help much appreciated ✋
