### ISSUE TITLE
[Bug]: The blank placeholder of the list item coincides with the cursor.

### ISSUE THREAD

**Issue by werct** [ueberdosis/tiptap#5517]
### Affected Packages

extension-placeholder

### Version(s)

2.6.4

### Bug Description

![image](https://github.com/user-attachments/assets/a359411f-f1c5-42d4-b861-c0c140e04929)
```javascript
import StarterKit from '@tiptap/starter-kit'
import Placeholder from '@tiptap/extension-placeholder'

const editor = useEditor({
  extensions: [
    StarterKit,
    Placeholder.configure({
      // BUG:
      placeholder: 'input / evoke more',
    }),

  ],
  content: ``,
  editorProps: {
    attributes: {
      class: 'focus:outline-none',
    },
  },
})
```
I used Tailwind CSS.

### Browser Used

Chrome

### Expected Behavior

The blank placeholder of the list item coincides with the cursor.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by werct** [comment]
```css
<style lang="less">
/* Basic editor styles */
.tiptap {
  .is-empty::before {
    color: rgb(209 213 219);;
    content: attr(data-placeholder);
    float: left;
    height: 0;
    pointer-events: none;
  }

  .is-empty.is-editor-empty {
    li {
      padding: 0;
    }
  }
}
</style>
```
This is my current solution

**Comment by aryamantodkar** [comment]
@werct  is this fixed? I can't reproduce this locally.

**Comment by werct** [comment]
@aryamantodkar It has been solved. There was a problem with the way I wrote my CSS. I wrote it like this:
```css
.tiptap {
  .is-empty::before {
    color:  #adb5bd;
    content: attr(data-placeholder);
    float: left;
    height: 0;
    pointer-events: none;
  }
}
```
It should be like this:
```css
.tiptap p.is-empty::before {
  color: #adb5bd;
  content: attr(data-placeholder);
  float: left;
  height: 0;
  pointer-events: none;
}
```

Thank you for your reply.
