### ISSUE TITLE
[Bug]: Contenteditable Loses Focus on Safari (macOS Monterey 12.6)

### ISSUE THREAD

**Issue by tance77** [ueberdosis/tiptap#6187]
### Affected Packages

core

### Version(s)

2.11.5

## Issue
On Safari (macOS Monterey 12.6), the contenteditable element loses focus every time the user types or attempts to click into it.

## Steps to Reproduce
1. Open Safari on macOS Monterey 12.6.
2. Navigate to a page with a contenteditable element.
3. Click inside the contenteditable element and start typing.
4. Notice that the element loses focus immediately upon interaction.

## Expected Behavior
The contenteditable element should retain focus while the user types or clicks inside it.

## Actual Behavior
The element loses focus upon typing or clicking, making it unusable.

## Fix
The issue is resolved by explicitly setting -webkit-user-select: text; in CSS:

```css
[contenteditable] {
    -webkit-user-select: text; /* Required for Safari to prevent focus loss */
    user-select: text;
}
```

## Additional Notes
* This behavior appears to be specific to Safari on macOS Monterey 12.6.
* Other browsers (e.g., Chrome, Firefox) do not exhibit this issue.

### Browser Used

Safari

### Expected Behavior

 .

### Dependency Updates

- [x] Yes, I've updated all my dependencies.
