### ISSUE TITLE
Multi column layout plugin

### ISSUE THREAD

**Issue by websiddu** [ueberdosis/tiptap#638]
First of I want to thank you for your amazing work. I know this might be a question for the prosemirror team. 

But I would really really love an example of a multi column layout plugin like [here](https://atlaskit.atlassian.com/examples/editor/editor-core/full-page). 

![image](https://user-images.githubusercontent.com/968912/77400257-1c79eb80-6d68-11ea-9f79-5dd4866b2636.png)

It would be amazing to have this one feature to make it extremely powerful webpage builder tool.

**Comment by hanspagel** [comment]
Oh, that looks like a lot of work! Thanks for the suggestion! I added this to the list of ideas for new extensions for tiptap v2. 

I’m closing this for now. ✌️

**Comment by DanAndreasson** [comment]
Are there any plans for this? We need this and I wonder if I should try to implement it myself or if it's on the way?

**Comment by ctwhome** [comment]
I second this feature

**Comment by leonard-henriquez** [comment]
I just started to develop an extension to support multicolumn layout.
I plan to opensource it as a public package, so I would love to have your feedback to improve it! 🙏 

The extension introduce 3 new commands:
- `setColumns(n)` to add `n` new columns on an existing node (with the existing content)
- `insertColumns(n)` to add `n` new columns on an empty node
- `unsetColumns()` to remove columns (and drop its content, unfortunately...) 

Here is a quick preview of the features:
[Column extension for Tiptap - Watch Video](https://www.loom.com/share/019ec6d12dc74334aae7e41fb57eb0a0)

You can check the code and create a PR from here:
https://codesandbox.io/p/github/leonard-henriquez/column-extension/main

PS: Please be gentle, I just started to learn typescript a few weeks ago and Tiptap this week 😊

**Comment by ctwhome** [comment]
It starting to look good! Are you planing to make it responsive,  probably
folding from 3 columns to 1 on smaller devices?

**Comment by leonard-henriquez** [comment]
There are classes on the container and the columns so you can customize it however you want 😊 

The dom looks like this:
<img width="227" alt="Capture d’écran 2022-08-17 à 00 31 41" src="https://user-images.githubusercontent.com/30215564/184996462-b9476b4f-8a99-473d-a0e0-2351fc3d39af.png">

And the default styling is this one:
```css
.ProseMirror .column-block {
  width: 100%;
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: 1fr;
  gap: 24px;
  padding: 8px 0;
}

.ProseMirror .column {
  overflow: auto;
  border: 1px gray dashed;
  border-radius: 8px;
  padding: 8px;
  margin: -8px;
}
```
